name = "Create With"
author = "hothod2nd"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "693e7be9a6d6e5868128d117740fc36620f0c7b18cf8e271284ab75a835b7a03"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
